### ISSUE TITLE
Numbering isn't showing up for desktop

### ISSUE THREAD

**Issue by lanbozhou** [serpbook/spyglass#7]
For Features for each device:

This is what we want each device’s Spyglass to have.. it looks like the numbering isn’t working for desktop:
https://keyword.com/serp/spyglass?kwid=177988186%7C1698fb752ebd10b8c8da55375885bd60&ranking=2

**Comment by nikunjsardhara** [comment]
https://github.com/serpbook/spyglass/pull/6
