### ISSUE TITLE
Ads are counting

### ISSUE THREAD

**Issue by lanbozhou** [serpbook/spyglass#8]
ads should NOT be included etc in mobile

![image](https://user-images.githubusercontent.com/45627908/123370090-9e952900-d544-11eb-9933-f6048fe0270a.png)

**Comment by nikunjsardhara** [comment]
@lanbozhou It's fixed. Could you verify and close this issue?

**Comment by lanbozhou** [comment]
@nikunjsardhara i think looks good now
